### ISSUE TITLE
App crushing

### ISSUE THREAD

**Issue by zaied45-183** [Jatin141/IMA-SDK-Flutter#1]
Hi, I used your code to implement IMA into my flutter app. Initially, I got a lot of errors. Somehow I solved everything but when I'm trying to open my app it's crushing. Can you kindly help me?  [Urgent]

**Comment by Jatin141** [comment]
Hi @zaied45-183 Thanks for raised issue. can you please check native uikit view same as my file and check how the work method channel pass the data.

**Comment by zaied45-183** [comment]
Hi, thanks. It's worked. Now the issue is it's for native exoplayer. We're trying to implement it on Better Player: https://pub.dev/packages/better_player

**Comment by Jatin141** [comment]
Hi i am implement my player is native and this player i am use (https://github.com/wxxsw/GSPlayer)

**Comment by zaied45-183** [comment]
Hi, @Jatin141  May I get your contact info, please? Or can you knock me at "sohelcse1999@gmail.com" I'm looking for paid support.

**Comment by Jatin141** [comment]
@zaied45-183 you can check my ios native class you get batter idea. Thanks

**Comment by Jatin141** [comment]
@zaied45-183 if not work wait for some day i don't know how many days long because i am busy in other priority work. so i provide another demo. Thanks

**Comment by Jatin141** [comment]
@zaied45-183 Demo work this i am attach screen

Have you required full demo.

 [shot[](url)](url
![Simulator Screen Shot - iPhone 13 - 2022-08-06 at 13 26 12](https://user-images.githubusercontent.com/106056823/183240206-5eb36f3a-7b11-4dea-8b78-7971719a50f9.png)
![Simulator Screen Shot - iPhone 13 - 2022-08-06 at 13 26 15](https://user-images.githubusercontent.com/106056823/183240207-c7c2d6a0-418d-4cbe-a75e-051354dbaf2d.png)
)
